name: starter_architecture_flutter_firebase
description: A new Flutter project.

publish_to: 'none'
version: 1.0.2+2

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.9.2
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.10.0
  firebase_core: ^2.19.0
  firebase_ui_auth: ^1.8.0
  firebase_ui_firestore: ^1.5.11
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.1
  flutter_svg: ^2.0.7
  go_router: 11.1.1
  intl: ^0.18.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.1
  # the annotation package containing @riverpod
  riverpod_annotation: 2.1.6
  firebase_ui_localizations: ^1.7.1
  firebase_ui_oauth_google: ^1.2.13
  google_sign_in: ^6.1.5
  calendar_date_picker2: ^0.5.3
  table_calendar: ^3.0.9
  flutter_onboarding_slider: ^1.0.11
  carousel_slider: ^4.2.1
  riverpod_generator: ^2.3.3
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  random_string: ^2.3.1
  flutter_lints: ^2.0.3
  # a tool for running code generators
  build_runner: ^2.4.6
  # the code generator
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: ^2.3.2
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: 0.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/time-tracking.svg
    - assets/images/logo.png
    - assets/json/bible-RNKSV.json
